name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        rust: [stable, beta, nightly]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: check
    - uses: actions-rs/cargo@v1
      with:
        command: build
    - run: rustup component add rustfmt
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    # - name: Build development
    #   run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose
    # - name: Build release
    #   run: cargo build --verbose --release --target-dir ./build
    # - name: tar
    #   run: tar cvf simple-rust-cli.tar.gz ./build/release/simple-rust-cli* 