name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        rust: [stable, beta, nightly]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      name: Install ${{ matrix.rust }}
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions-rs/cargo@v1
      name: Cargo check
      with:
        command: check
    - run: rustup component add rustfmt
    - uses: actions-rs/cargo@v1
      name: Cargo fmt
      with:
        command: fmt
        args: --all -- --check
    - uses: actions-rs/cargo@v1
      name: Cargo test
      with:
        command: test
        args: --verbose
    - uses: actions-rs/cargo@v1
      name: Cargo build development
      with:
        command: build
    - uses: actions-rs/cargo@v1
      name: Cargo build release
      with:
        command: build 
        args: --verbose --release
    - name: tar
      run: |
        ls -alh ./target/
        ls -alh ./target/release/
        tar cvf simple-rust-cli-os-${{ matrix.os }}-rust-${{ matrix.rust }}.tar.gz -C ./target/release/ simple-rust-cli*        

    # - name: Build development
    #   run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose
    # - name: Build release
    #   run: cargo build --verbose --release --target-dir ./build
    # - name: tar
    #   run: tar cvf simple-rust-cli.tar.gz ./build/release/simple-rust-cli* 