name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
    CARGO_TERM_COLOR: always
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build development
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Build release
        run: cargo build --verbose --release --target-dir ./build
      - name: tar
        run: tar cvf simple-rust-cli.tar.gz ./build/release/simple-rust-cli* 
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: simple-rust-cli.tar.gz